export const categories = [
  { key: "purchases", name: "Compras", icon: "credit-card-fast", color: "#5636D3" },
  { key: "food", name: "Alimentação", icon: "food", color: "#FF872C" },
  { key: "car", name: "Carro", icon: "car", color: "#E83F5B" },
  { key: "leisure", name: "Lazer", icon: "skateboarding", color: "#26195C" },
  { key: "studies", name: "Estudos", icon: "bookshelf", color: "#9C001A" },
  { key: "light", name: "Luz", icon: "lightbulb", color: "#FFD700" },
  { key: "water", name: "Água", icon: "water", color: "#1E90FF" },
  { key: "internet", name: "Internet", icon: "access-point-network", color: "#000000" },
  { key: "market", name: "Mercado", icon: "cart-outline", color: "#FA9C29" },
  { key: "rental", name: "Aluguel", icon: "home", color: "#3cb371" },
  { key: "gas", name: "Gás", icon: "gas-cylinder", color: "#636363" },
  { key: "health", name: "Saúde", icon: "heart-flash", color: "#ff0000" },
  { key: "others", name: "Outros", icon: "robot-confused", color: "#a100ff" },
];
